/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import static tetris.FileManager.readFile;
import static tetris.FileManager.writeToFile;


/**
 *
 * @author jmque
 */
public class LeaderboardFrame extends javax.swing.JFrame {
    private String leaderboardFile = "leaderboard.txt";
    private ArrayList<Integer> scores;
    private ArrayList<String> names;
    
    /**
     * Creates new form LeaderBoardFrame
     */
    public LeaderboardFrame() {
        initComponents();
        names = new ArrayList<String>();
        scores = new ArrayList<Integer>();
        
    }
    
    public void addScore(String name, int score) {
        if(scores.isEmpty()) {
            scores.add(score);
            names.add(name);
        }
        
        else {
            for(int i = 0; i < scores.size(); i++) {
                if(score > scores.get(i)) {
                    scores.add(i, score);
                    names.add(i, name);
                    return;
                }
            }
            if(scores.size() < 10)  {
                scores.add(scores.size(), score);
                names.add(names.size(), name);
                    }
        }
    }

    public ArrayList<Integer> getScores() {
        return scores;
    }

    public ArrayList<String> getNames() {
        return names;
    }
    
    public String leaderboardString() {
        String leaderboard = "";
        int index = 10;
        if (names.size() < 10){
            index = names.size();
            System.out.println(names.get(0));
        }
        for(int i = 0; i < index; i++) {
            leaderboard += ((i + 1) + ". " + names.get(i) + ": " + scores.get(i));
            leaderboard += "\n";
        }
        return leaderboard;
    }
    
    public void save() throws FileNotFoundException, IOException {
        FileOutputStream fileOut = new FileOutputStream("scores.txt");
        ObjectOutputStream out = new ObjectOutputStream(fileOut);
        out.writeObject(scores);
        out.close();
        fileOut.close();
        FileOutputStream fileOut2 = new FileOutputStream("names.txt");
        ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
        out2.writeObject(names);
        out2.close();
        fileOut2.close();
    }
    
    public void load() throws FileNotFoundException, IOException, ClassNotFoundException {
        FileInputStream fileIn = new FileInputStream("scores.txt");
        ObjectInputStream in = new ObjectInputStream(fileIn);
        scores = (ArrayList<Integer>) in.readObject();
        FileInputStream fileIn2 = new FileInputStream("names.txt");
        ObjectInputStream in2 = new ObjectInputStream(fileIn2);
        names = (ArrayList<String>) in2.readObject();
    }
    
    
    public void createFile (String path) throws IOException{
        File myObj = new File(path);
        FileWriter myWriter = new FileWriter(path, true);
        
          myWriter.close();
    }
    
    public void saveLeaderboard(String username, int score) throws IOException{
        
        String path = System.getProperty("user.dir") + "/" + "/leaderboard.txt";
        createFile(path);
        
        writeToFile(path, username + "\t");
        writeToFile(path, Integer.toString(score) + "\n");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLeaderboard = new javax.swing.JTextArea();
        lblLeaderboardHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leaderboard");
        setResizable(false);

        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnMenu.setText("Main Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        txaLeaderboard.setEditable(false);
        txaLeaderboard.setColumns(20);
        txaLeaderboard.setRows(5);
        jScrollPane1.setViewportView(txaLeaderboard);

        lblLeaderboardHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLeaderboardHeader.setText("Top 10 Players");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLeaderboardHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLeaderboardHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);
        Tetris.showStartup();
    }//GEN-LAST:event_btnMenuActionPerformed

    public void refreshText() {
        txaLeaderboard.setText(leaderboardString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLeaderboardHeader;
    private javax.swing.JTextArea txaLeaderboard;
    // End of variables declaration//GEN-END:variables
}
